### Working with Numpy - for mathematical operations

```
pip install numpy
```

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,2]) #iterable
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5 2]
<class 'numpy.ndarray'>
(6,)


In [5]:
b = np.array([[[1]],[[2]],[[3]],[[4]],[[5]]])
print(b)
print(b.shape)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]
(5, 1, 1)


In [8]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [19]:
# Create Zeros, Ones, Custom array
a = np.zeros((3,3))
print(a)

b = np.ones((2,3))
print(b)

#Array of some constants
c = np.full((3,2),5)
print(c)

#Identity Matrix - Size/Square matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((2,3))
print(randomMatrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.44745186 0.01253507 0.09447295]
 [0.02527012 0.46501319 0.34163422]]


In [21]:
print(randomMatrix[:,2])

[0.09447295 0.34163422]


In [23]:
randomMatrix[:,2].shape

(2,)

In [18]:
randomMatrix[1,1:3] = 1 # Slicing
print(randomMatrix)

[[0.37754576 0.43131543 0.62769984]
 [0.98280604 1.         1.        ]]


In [39]:
## Set some rows and columns with any values
z = np.zeros((3,3),dtype = np.int64)
z[1, :] = 5.02
print(z)
z[:,-1] = 7
print(z)


[[0 0 0]
 [5 5 5]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [40]:
# Datatypes 
print(z.dtype)

int64


In [46]:
#Matematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Element Wise Addition
print(x + y)
print(np.add(x,y))
print(x - y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [47]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [48]:
# Matrix Multiplication / Dot Products
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [80]:
#Multiplication(Dot Product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))



30


In [50]:
print(a)

[1 2 3 4]


In [51]:
print(sum(a))

10


In [52]:
print(x)

[[1 2]
 [3 4]]


In [57]:
print(np.sum(x))
print(np.sum(x,axis=1))

10
[3 7]


In [68]:
y = np.random.randint(1, 5, size=(2,2,2))

In [71]:
print(y)

[[[1 1]
  [3 2]]

 [[4 1]
  [3 4]]]


In [73]:
np.sum(y, axis=1)

array([[4, 3],
       [7, 5]])

In [82]:
# Stacking of arrays
print(a)
b = b + 5
print(b)
print(a.shape, b.shape)

[1 2 3 4]
[11 12 13 14]
(4,) (4,)


In [85]:
stacked = np.stack((a,b),axis=1)

In [86]:
print(stacked.shape)

(4, 2)


In [87]:
print(stacked)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]


In [89]:
stacked.shape

(4, 2)

In [90]:
stacked.reshape((2, 4))

array([[ 1, 11,  2, 12],
       [ 3, 13,  4, 14]])

In [98]:
# Reshape a Numpy Array
# print(a)
stacked_reshape = stacked.reshape((-1, 2,2))
print(stacked_reshape)
print(stacked_reshape.shape)

[[[ 1 11]
  [ 2 12]]

 [[ 3 13]
  [ 4 14]]]
(2, 2, 2)


# Some More Numpy Functions - Statistics
- min, max
- mean 
- median
- average
- variance
- standard deviation


In [99]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))



[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [99]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [111]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# Mean vs Average is Weighted
print(np.mean(c))

# Weights 
w = np.array([1,1,1,1,1])
print(np.average(c,weights=w))

# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

#Inbuilt Function
dev= np.std(c)
print(dev)

#Variance
print(myStd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


# Numpy Random Module

- rand : Random values in a given shape.
- randn : Return a sample (or samples) from the “standard normal” distribution.
- randint : Return random integers from low (inclusive) to high (exclusive).
- random : Return random floats in the half-open interval [0.0, 1.0) 
- choice : Generates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [116]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [117]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [134]:
#Returns values from a Standard Normal Distributions
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,size=(3,5))
print(a)

#Randoly pick one element from a array
element = np.random.choice([1,4,3,2,11,27], size=2, p=[0.75, 0.20, 0.05, 0, 0, 0])
print(element)


[[-1.20102365 -0.07904398  0.78989335]
 [ 2.18617751 -0.926691    0.40184526]]
[[5 5 9 8 9]
 [8 8 9 5 8]
 [6 9 9 8 7]]
[4 4]


# Broadcasting

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

- they are equal, or

- one of them is 1

If these conditions are not met, a ```ValueError: operands could not be broadcast together``` exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

In [140]:
a = np.array([1,2,3])

a + 5

array([6, 7, 8])

In [141]:
a + np.array([5,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [142]:
m = np.random.randint(0, 5, size=(2, 3))

In [149]:
b = np.random.randint(0, 5, size=(3,))

In [146]:
m

array([[2, 0, 2],
       [1, 2, 3]])

In [150]:
b

array([1, 3, 3])

In [151]:
(m + b).shape

(2, 3)

In [152]:
m + b

array([[3, 3, 5],
       [2, 5, 6]])

In [153]:
m1 = np.random.randint(1, 5, size=(3,1,2))
m2 = np.random.randint(1, 5, size=(3,1))

In [155]:
m1

array([[[2, 3]],

       [[4, 3]],

       [[2, 4]]])

In [156]:
m2

array([[4],
       [4],
       [3]])

In [154]:
m1+m2

array([[[6, 7],
        [6, 7],
        [5, 6]],

       [[8, 7],
        [8, 7],
        [7, 6]],

       [[6, 8],
        [6, 8],
        [5, 7]]])

In [157]:
(m1+m2).shape

(3, 3, 2)

In [161]:
assert m1.shape == m2.shape, f"Shape mismatch between m1 {m1.shape} & m2 {m2.shape}"

AssertionError: Shape mismatch between m1 (3, 1, 2) & m2 (3, 1)